# Generated by Django 4.2.11 on 2024-04-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_official_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
