# Generated by Django 4.2.11 on 2024-04-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_vehicle_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Official',
        ),
    ]
