# Generated by Django 4.2.11 on 2024-04-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_delete_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('licence', models.CharField(max_length=100)),
                ('date_incidence', models.DateTimeField(auto_now_add=True)),
                ('official_comment', models.TextField()),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.vehicle')),
            ],
        ),
    ]
