# Generated by Django 4.2.11 on 2024-04-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_violation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='violation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
